### ISSUE TITLE
[BUG] compile error in TileEntityHamsterWheel.java and TileEntityHive.java

### ISSUE THREAD

**Issue by Tsoccerguy3** [capnkirok/animaniamod#275]
### Expected Behavior
Current code fails to compile with new "CraftStudio-1.0.1.95-mc1.12-alpha-dev.jar"
methods need update

/home/wds/dev/animaniamod/build/sources/main/java/com/animania/common/tileentities/TileEntityHamsterWheel.java:64: error: abstract method update() in ITickable cannot be accessed directly
                super.update();
                     ^
/home/wds/dev/animaniamod/build/sources/main/java/com/animania/common/tileentities/TileEntityHive.java:59: error: abstract method update() in ITickable cannot be accessed directly
                super.update();

### Actual Behavior
wds@wds-GP72-6QF:~/dev/animaniamod$ gradle build
Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details
This mapping 'snapshot_20171003' was designed for MC 1.12! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-3996470        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
                 Powered by MCP                  
             http://modcoderpack.com             
     by: Searge, ProfMobius, R4wk, ZeuX          
     Fesh0r, IngisKahn, bspkrs, LexManos         
#################################################
Cleaned up directory '/home/wds/dev/animaniamod/build/classes/main'
:extractMcpMappings SKIPPED
:deobfCompileDeobfDepTask0 SKIPPED
:deobfCompileDeobfDepTask1
:deobfCompileDeobfDepTask2 SKIPPED
:deobfCompileDeobfDepTask3 SKIPPED
:deobfCompileDeobfDepTask4 SKIPPED
:deobfCompileDeobfDepTask5 SKIPPED
:deobfCompileDeobfDepTask6
:deobfCompileRemapDepSourcesTask10 SKIPPED
:deobfCompileRemapDepSourcesTask11 SKIPPED
:deobfCompileRemapDepSourcesTask12 SKIPPED
:deobfCompileRemapDepSourcesTask7 SKIPPED
:deobfCompileRemapDepSourcesTask8 SKIPPED
:deobfCompileRemapDepSourcesTask9 SKIPPED
:deobfCompileDummyTask
:getVersionJson
:extractUserdev
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches SKIPPED
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:genSrgs SKIPPED
:deobfMcMCP SKIPPED
:sourceApiJava
:compileApiJava NO-SOURCE
:processApiResources NO-SOURCE
:apiClasses UP-TO-DATE
:sourceMainJava
:compileJava
/home/wds/dev/animaniamod/build/sources/main/java/com/animania/common/tileentities/TileEntityHamsterWheel.java:64: error: abstract method update() in ITickable cannot be accessed directly
                super.update();
                     ^
/home/wds/dev/animaniamod/build/sources/main/java/com/animania/common/tileentities/TileEntityHive.java:59: error: abstract method update() in ITickable cannot be accessed directly
                super.update();
                     ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 49.68 secs
wds@wds-GP72-6QF:~/dev/animaniamod$

**Comment by Tsoccerguy3** [comment]
Fixed , updated Forge to current 1.12.2 b2808 , mappings stable_39 , gradle 5.1
updated all methods that error out on build . Advise to do updates for newer compatibility
